# Generated by Django 6.0 on 2025-12-27 15:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='service_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('type_of_work', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='history.party')),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcs', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('record_date', models.DateField(default=django.utils.timezone.now)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('p', 'Paid'), ('d', 'Due'), ('par', 'Partial')], default='d', max_length=3)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='history.party')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='history.service_type')),
            ],
        ),
        migrations.CreateModel(
            name='allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='history.payment')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='history.record')),
            ],
        ),
        migrations.CreateModel(
            name='work_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.party')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.service_type')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('party', 'service_type'), name='unique_party_service_type_rate')],
            },
        ),
    ]
