# Generated by Django 6.0 on 2026-01-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
