# Generated by Django 6.0 on 2026-01-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'permissions': [('cancel_record', 'can cancel record')]},
        ),
    ]
