# Generated by Django 6.0 on 2026-01-24 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_record_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_rate_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='rate_mode',
            field=models.CharField(choices=[('system', 'system'), ('custom', 'custom')], default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('model_name', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('DELETE', 'DELETE'), ('UPDATE', 'UPDATE')], max_length=10)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
