# Generated by Django 6.0 on 2026-01-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_record_is_rate_manual_record_rate_mode_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='is_rate_manual',
        ),
        migrations.RemoveField(
            model_name='record',
            name='rate_mode',
        ),
    ]
