# Generated by Django 6.0 on 2026-01-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_review_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Note',
        ),
    ]
