# Generated by Django 6.0 on 2026-01-24 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_remove_record_is_rate_manual_remove_record_rate_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
