# Generated by Django 6.0 on 2026-01-12 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_rename_review_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.RemoveField(
            model_name='party',
            name='email',
        ),
        migrations.RemoveField(
            model_name='party',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='party',
            name='last_name',
        ),
        migrations.AddField(
            model_name='party',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
