# Generated by Django 6.0 on 2026-01-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_alter_party_options_remove_party_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'permissions': [('cancel_record', 'can cancel a record')]},
        ),
    ]
