# Generated by Django 6.0 on 2026-01-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_remove_party_advance_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='short',
            field=models.CharField(default='s', max_length=10),
            preserve_default=False,
        ),
    ]
