# Generated by Django 6.0 on 2026-01-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_party_short'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='short',
            new_name='logo',
        ),
    ]
