# Generated by Django 6.0 on 2026-01-26 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_rename_short_party_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.party'),
        ),
    ]
