# Generated by Django 6.0 on 2026-01-26 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_auditlog_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.party'),
        ),
    ]
