# Generated by Django 6.0 on 2026-01-27 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0010_alter_auditlog_party'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
