# Generated by Django 6.0 on 2026-01-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0011_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
