# Generated by Django 6.0 on 2026-01-29 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0012_alter_party_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_type',
            name='type_of_work',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='service_type',
            constraint=models.UniqueConstraint(fields=('user', 'type_of_work'), name='unique_user_type_of_work'),
        ),
    ]
