# Generated by Django 6.0 on 2026-01-31 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0014_alter_party_email_party_unique_user_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='party',
            name='unique_user_email',
        ),
        migrations.AlterField(
            model_name='party',
            name='logo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
