# Generated by Django 6.0 on 2026-02-12 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0015_alter_party_options_remove_party_unique_user_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advanceledger',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-record_date', '-pk'], 'permissions': [('cancel_record', 'can cancel record')]},
        ),
        migrations.AlterModelOptions(
            name='service_type',
            options={'ordering': ['type_of_work']},
        ),
        migrations.AlterModelOptions(
            name='work_rate',
            options={'ordering': ['rate']},
        ),
        migrations.AddField(
            model_name='party',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employ', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='party',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Payment_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('A', 'APPROVED'), ('R', 'REJECTED')], default='P', max_length=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.party')),
                ('record', models.ManyToManyField(to='history.record')),
            ],
        ),
    ]
