# Generated by Django 6.0 on 2026-02-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0016_alter_advanceledger_options_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_request',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
