# Generated by Django 6.0 on 2026-02-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0017_payment_request_rejected_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment_request',
            options={'ordering': ['-created_at', '-pk']},
        ),
    ]
