# Generated by Django 6.0 on 2026-03-24 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0018_alter_payment_request_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment_request',
            options={'ordering': ['-pk']},
        ),
    ]
