# Generated by Django 6.0 on 2026-04-05 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0019_alter_payment_request_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_request',
            name='party',
        ),
    ]
